### ISSUE TITLE
Epic for Bindings Rebuild

### ISSUE THREAD

**Issue by matthewkeil** [ChainSafe/blst-ts#88]
# Rebuilding `blst-ts`

Adding this issue as a tracker for rebuilding the bindings using `N-API`.  There is not much code that is shared between the new and old versions so the ease the review process I am going to break stuff up into pieces.  I am thinking about using `mkeil/rebuild` as the trunk branch and will merge all the pieces below into it.  I think once everything is merged there may be a a PR to organize a bit and remove the stuff related to swig before merging `mkeil/rebuild` to `master`.

## Review/Merge Hierarchy

Most of these PR's cascade.  I was attempting to do the base Classes and then keep all the functions independent but there were a few changes in `verifyMultipleAggregateSignatures` that should cascade to avoid difficult merge conflicts for the `verify` suite.  Fixed the branch in PR#97 and merged the aggregates into the verify branch to test `fastAggregateVerify`.  Any remaining PR's will follow from #97 to avoid similar confusion.

#89 -> #90 -> #91 -> #94 -> this is where there is a branch.

branch 1) #94 -> #92 -> #93
branch 2) #94 -> #95 -> #96

branches get merged together in) #97

#97 -> #98 -> #99 -> #100->#101

All unit tests and all specs are passing.  The bulk of the code is substantially complete.  Just the PR review changes and ancillary code (CI/CD etc) needs to be completed.

The implementation for this code in Lodestar can be found here:
- https://github.com/ChainSafe/lodestar/pull/5493

## Reviewer Notes

There is a lot of code in here and the first few pieces are mostly boilerplate to make the rest work.  It may be easier to take a peek at #92 to see how everything comes together and gets implemented.  Then peek at #91 and #94 to get an overview of the pki classes.  Then circle back and start reviewing #90.

To view the entire lot at once, [`mkeil/fix-agg-spec`](https://github.com/ChainSafe/blst-ts/tree/mkeil/fix-agg-spec/rebuild) has all of the pieces and is 100% passing specs and unit tests.

## Base
- [X] Folder structure and config files
    - #89

## Classes
- [ ] Rebuild `Addon`, `BlstBase`, `BlstAsyncWorker`, `Uint8ArrayArg`, `Uint8ArrayArgArray`
    - #90 
- [ ] Rebuild `SecretKey`, `PublicKey` and `Signature`
    - #91 
- [ ] Add `PublicKeyArg`, `PublicKeyArgArray`, `SignatureArg` and `SignatureArgArray`
    - #94
- [ ] Spec test for `SecretKey.sign`
    - #99  

## `aggregatePublicKey` and `aggregateSignatures`
- [ ] Rebuild aggregation functions with unit tests
    - #92 
- [ ] Aggregation Spec tests
    - #93  
- [ ] Pass x40 spec test
    - #100

## `verifyMultipleAggregateSignatures`
- [ ] Rebuild `verifyMultipleAggregateSignatures` function with unit tests
     - #95

## `verify` and  `aggregateVerify`
- [ ] Rebuild function with unit and spec tests
    - #96 

## `fastAggregateVerify`
- [ ] `fastAggregateVerify` unit and Spec tests (also covers merge of all function PR's)
    - #98

## Cross-Compatability
- [ ] Debug for linux builds
    - #101
- [ ] Debug for windows builds

## Things to double check
- [ ] `HandleScope` is applied correctly everywhere
- [x] Passing by `const &` everywhere applicable

## Wishlist
- [ ] Add validate param to `Signature.deserialize` 
- [ ] Add validate param to `PublicKey.deserialize`
- [ ] If single key or sig is passed to aggregate just pass through function and don't aggregate

## Testing
- [ ] Add `valgrind` leak check test
- [X] Add spec tests
- [x] Add benchmark tests
- [x] Performance comparison tests to old bindings

## DevOps
- [x] Update workflows for push/merge
    - #101
- [x] Create workflow to `node-pre-gyp` or `prebuild` for popular platforms
- [x] Update install script to reference pre-built bindings

## Integration/E2E Testing
- [x] Publish alpha set of updated bindings (or create Dockerfile using updated code)
- [ ] Determine telemetry that should be collected and compared for runtime testing
- [ ] Flamegraph for CPU tuning
- [ ] Heapdumps for memory tuning

## Audit
- [ ] Assess if external review/audit is prudent

## Documentation
- [x] Add docs before PR process for team
    - https://github.com/ChainSafe/blst-ts/pull/86
- [x] Update README.md
- [ ] Update CONTRIBUTING.md
- [ ] PR/Issue Node for `HandleScope`
    - https://github.com/nodejs/node/issues/47504

**Comment by matthewkeil** [comment]
@wemeetagain @g11tech @nazarhussain @tuyennhv @nflaig was curious if you guys had any thoughts about the process

**Comment by wemeetagain** [comment]
i think this can be closed since 1.0 has been released :)
